import { Router } from "express";
import argon2 from "argon2";
import sanitizeHtml from "sanitize-html";
import { prisma } from "../config/prisma.js";
import { requireAuth, requireRole } from "../middlewares/auth.js";
import { validate } from "../middlewares/validate.js";
import { bookSchema } from "../validators/schemas.js";
import { uploadImage } from "../middlewares/upload.js";
import { uploadBuffer, destroyImage } from "../services/upload.service.js";
import { approveBorrow, returnBorrow } from "../services/borrow.service.js";
import { audit } from "../services/audit.service.js";
import { AppError } from "../utils/AppError.js";
import { ok, page } from "../utils/response.js";
import { publishNotificationChange, subscribeToAdminActivity } from "../services/notification.service.js";

export const adminRouter = Router();
adminRouter.use(requireAuth, requireRole("ADMIN", "SUPER_ADMIN"));
const slugify = (value) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/đ/g,"d").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
const clean = (value) => typeof value === "string" ? sanitizeHtml(value, { allowedTags: ["p","br","strong","em","ul","ol","li","blockquote"], allowedAttributes: {} }) : value;
const paginationParams = (req, defaultLimit = 20) => ({ currentPage: Math.max(1, Number(req.query.page) || 1), limit: Math.min(100, Math.max(1, Number(req.query.limit) || defaultLimit)) });
const paged = async (req, res, delegate, args = {}, defaultLimit = 20) => {
  const { currentPage, limit } = paginationParams(req, defaultLimit);
  const [items, total] = await prisma.$transaction([
    delegate.findMany({ ...args, skip: (currentPage - 1) * limit, take: limit }),
    delegate.count({ where: args.where }),
  ]);
  return page(res, items, total, currentPage, limit);
};

adminRouter.get("/dashboard/stats", async (_req, res) => {
  const [books,copies,borrowing,overdue,unpaidFine,users,feedback,pendingReviews,topBooks,overdueList] = await Promise.all([
    prisma.book.count({ where: { deletedAt:null } }), prisma.bookCopy.count({ where:{deletedAt:null} }), prisma.borrowRecord.count({where:{status:"BORROWING"}}), prisma.borrowRecord.count({where:{status:"OVERDUE"}}), prisma.fine.aggregate({where:{status:"UNPAID"},_sum:{finalAmount:true}}), prisma.user.count({where:{deletedAt:null}}), prisma.feedback.count({where:{status:{in:["NEW","IN_PROGRESS"]}}}), prisma.review.count({where:{status:"PENDING"}}), prisma.book.findMany({where:{deletedAt:null},orderBy:{borrowCount:"desc"},take:5,select:{id:true,title:true,borrowCount:true,coverUrl:true}}), prisma.borrowRecord.findMany({where:{status:"OVERDUE"},include:{book:{select:{title:true}},user:{select:{firstName:true,lastMiddleName:true,email:true}},bookCopy:{select:{copyCode:true}}},orderBy:{dueDate:"asc"},take:8})
  ]);
  return ok(res,{books,copies,borrowing,overdue,unpaidFine:Number(unpaidFine._sum.finalAmount||0),users,feedback,pendingReviews,topBooks,overdueList});
});
adminRouter.get("/dashboard/activity", async (_req, res) => {
  const [users, borrows, reviews, feedbackItems, pendingBorrows, pendingReviews, pendingFeedback] = await Promise.all([
    prisma.user.findMany({ where: { deletedAt: null, role: "USER" }, select: { id: true, firstName: true, lastMiddleName: true, email: true, createdAt: true }, orderBy: { createdAt: "desc" }, take: 10 }),
    prisma.borrowRecord.findMany({ select: { id: true, status: true, createdAt: true, user: { select: { firstName: true, lastMiddleName: true } }, book: { select: { title: true } } }, orderBy: { createdAt: "desc" }, take: 10 }),
    prisma.review.findMany({ select: { id: true, rating: true, status: true, createdAt: true, user: { select: { firstName: true, lastMiddleName: true } }, book: { select: { title: true } } }, orderBy: { createdAt: "desc" }, take: 10 }),
    prisma.feedback.findMany({ select: { id: true, subject: true, status: true, createdAt: true, user: { select: { firstName: true, lastMiddleName: true } } }, orderBy: { createdAt: "desc" }, take: 10 }),
    prisma.borrowRecord.count({ where: { status: "PENDING" } }),
    prisma.review.count({ where: { status: "PENDING" } }),
    prisma.feedback.count({ where: { status: { in: ["NEW", "IN_PROGRESS"] } } }),
  ]);
  const name = (user) => `${user.lastMiddleName} ${user.firstName}`.trim();
  const items = [
    ...users.map((item) => ({ id: `user:${item.id}`, kind: "REGISTER", title: "Đăng ký tài khoản mới", message: `${name(item)} · ${item.email}`, createdAt: item.createdAt, href: "/admin/nguoi-dung" })),
    ...borrows.map((item) => ({ id: `borrow:${item.id}`, kind: "BORROW", title: item.status === "PENDING" ? "Yêu cầu mượn sách mới" : "Phiếu mượn được cập nhật", message: `${name(item.user)} · ${item.book.title}`, createdAt: item.createdAt, href: "/admin/muon-tra", status: item.status })),
    ...reviews.map((item) => ({ id: `review:${item.id}`, kind: "REVIEW", title: "Đánh giá sách mới", message: `${name(item.user)} đánh giá ${item.rating} sao · ${item.book.title}`, createdAt: item.createdAt, href: "/admin/danh-gia", status: item.status })),
    ...feedbackItems.map((item) => ({ id: `feedback:${item.id}`, kind: "FEEDBACK", title: "Góp ý mới", message: `${name(item.user)} · ${item.subject}`, createdAt: item.createdAt, href: "/admin/gop-y", status: item.status })),
  ].sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt)).slice(0, 15);
  return ok(res, { items, pending: { borrows: pendingBorrows, reviews: pendingReviews, feedback: pendingFeedback, total: pendingBorrows + pendingReviews + pendingFeedback } });
});
adminRouter.get("/dashboard/activity/stream", (req, res) => {
  res.status(200).set({ "Content-Type": "text/event-stream", "Cache-Control": "no-cache, no-transform", Connection: "keep-alive", "X-Accel-Buffering": "no" });
  res.flushHeaders?.();
  res.write(`event: connected\ndata: ${JSON.stringify({ at: new Date().toISOString() })}\n\n`);
  const push = (event) => res.write(`event: admin_activity\ndata: ${JSON.stringify(event)}\n\n`);
  const unsubscribe = subscribeToAdminActivity(push);
  const heartbeat = setInterval(() => res.write(`: heartbeat ${Date.now()}\n\n`), 25000);
  const lifetime = setTimeout(() => { res.write("event: reconnect\ndata: {}\n\n"); res.end(); }, 14 * 60 * 1000);
  let closed = false;
  const close = () => { if (closed) return; closed = true; clearInterval(heartbeat); clearTimeout(lifetime); unsubscribe(); };
  req.on("close", close);
  res.on("close", close);
});
adminRouter.get("/notifications", async (req, res) => {
  const { currentPage, limit } = paginationParams(req, 10);
  const adminFilter = { userId: req.user.id, data: { path: ["adminActivity"], equals: true } };
  const where = { ...adminFilter, ...(req.query.unread === "true" ? { readAt: null } : {}) };
  const [items, total, unreadCount, pendingBorrows, pendingReviews, pendingFeedback] = await prisma.$transaction([
    prisma.notification.findMany({ where, orderBy: [{ createdAt: "desc" }, { id: "desc" }], skip: (currentPage - 1) * limit, take: limit }),
    prisma.notification.count({ where }),
    prisma.notification.count({ where: { ...adminFilter, readAt: null } }),
    prisma.borrowRecord.count({ where: { status: "PENDING" } }),
    prisma.review.count({ where: { status: "PENDING" } }),
    prisma.feedback.count({ where: { status: { in: ["NEW", "IN_PROGRESS"] } } }),
  ]);
  return ok(res, { items, unreadCount, pending: { borrows: pendingBorrows, reviews: pendingReviews, feedback: pendingFeedback, total: pendingBorrows + pendingReviews + pendingFeedback }, pagination: { page: currentPage, limit, total, pages: Math.ceil(total / limit) } });
});
adminRouter.patch("/notifications/read-all", async (req, res) => {
  await prisma.notification.updateMany({ where: { userId: req.user.id, readAt: null, data: { path: ["adminActivity"], equals: true } }, data: { readAt: new Date() } });
  return ok(res, null, "Đã đọc tất cả thông báo Admin");
});
adminRouter.patch("/notifications/:id/read", async (req, res) => {
  const updated = await prisma.notification.updateMany({ where: { id: req.params.id, userId: req.user.id, data: { path: ["adminActivity"], equals: true } }, data: { readAt: new Date() } });
  if (!updated.count) throw new AppError(404, "Không tìm thấy thông báo Admin");
  return ok(res, null, "Đã đọc thông báo");
});
adminRouter.get("/metadata", async (_req,res)=>ok(res,{categories:await prisma.category.findMany({orderBy:{name:"asc"}}),authors:await prisma.author.findMany({orderBy:{name:"asc"}}),publishers:await prisma.publisher.findMany({orderBy:{name:"asc"}}),locations:await prisma.location.findMany({orderBy:[{area:"asc"},{cabinet:"asc"}]})}));
for (const [path, delegate, orderBy] of [
  ["categories", prisma.category, [{ name: "asc" }, { id: "asc" }]],
  ["authors", prisma.author, [{ name: "asc" }, { id: "asc" }]],
  ["publishers", prisma.publisher, [{ name: "asc" }, { id: "asc" }]],
  ["locations", prisma.location, [{ area: "asc" }, { cabinet: "asc" }, { shelf: "asc" }, { id: "asc" }]],
]) adminRouter.get(`/${path}`, (req, res) => paged(req, res, delegate, { orderBy }, 12));
adminRouter.post("/categories",async(req,res)=>ok(res,await prisma.category.create({data:{name:clean(req.body.name),slug:slugify(req.body.name),description:clean(req.body.description)}}),"Đã thêm thể loại",201));
adminRouter.post("/authors",async(req,res)=>ok(res,await prisma.author.create({data:{name:clean(req.body.name),bio:clean(req.body.bio)}}),"Đã thêm tác giả",201));
adminRouter.post("/locations",async(req,res)=>ok(res,await prisma.location.create({data:{area:clean(req.body.area),cabinet:clean(req.body.cabinet),shelf:clean(req.body.shelf),slot:clean(req.body.slot),note:clean(req.body.note)}}),"Đã thêm vị trí",201));
adminRouter.post("/publishers",async(req,res)=>ok(res,await prisma.publisher.create({data:{name:clean(req.body.name)}}),"Đã thêm nhà xuất bản",201));

adminRouter.patch("/categories/:id",async(req,res)=>{const before=await prisma.category.findUnique({where:{id:req.params.id}});if(!before)throw new AppError(404,"Không tìm thấy thể loại");const name=clean(req.body.name);const item=await prisma.category.update({where:{id:req.params.id},data:{...(name?{name,slug:slugify(name)}:{}),...(req.body.description!==undefined?{description:clean(req.body.description)}:{})}});await audit({req,action:"CATEGORY_UPDATED",entityType:"Category",entityId:item.id,before,after:item});return ok(res,item,"Đã cập nhật thể loại")});
adminRouter.delete("/categories/:id",async(req,res)=>{const item=await prisma.category.findUnique({where:{id:req.params.id},include:{_count:{select:{books:true}}}});if(!item)throw new AppError(404,"Không tìm thấy thể loại");if(item._count.books)throw new AppError(409,"Không thể xóa thể loại đang có sách");await audit({req,action:"CATEGORY_DELETED",entityType:"Category",entityId:item.id,before:{name:item.name}});await prisma.category.delete({where:{id:item.id}});return ok(res,null,"Đã xóa thể loại")});
adminRouter.patch("/authors/:id",async(req,res)=>{const before=await prisma.author.findUnique({where:{id:req.params.id}});if(!before)throw new AppError(404,"Không tìm thấy tác giả");const item=await prisma.author.update({where:{id:req.params.id},data:{...(req.body.name?{name:clean(req.body.name)}:{}),...(req.body.bio!==undefined?{bio:clean(req.body.bio)}:{})}});await audit({req,action:"AUTHOR_UPDATED",entityType:"Author",entityId:item.id,before,after:item});return ok(res,item,"Đã cập nhật tác giả")});
adminRouter.delete("/authors/:id",async(req,res)=>{const item=await prisma.author.findUnique({where:{id:req.params.id},include:{_count:{select:{books:true}}}});if(!item)throw new AppError(404,"Không tìm thấy tác giả");if(item._count.books)throw new AppError(409,"Không thể xóa tác giả đang có sách");await audit({req,action:"AUTHOR_DELETED",entityType:"Author",entityId:item.id,before:{name:item.name}});await prisma.author.delete({where:{id:item.id}});return ok(res,null,"Đã xóa tác giả")});
adminRouter.patch("/publishers/:id",async(req,res)=>{const before=await prisma.publisher.findUnique({where:{id:req.params.id}});if(!before)throw new AppError(404,"Không tìm thấy nhà xuất bản");const item=await prisma.publisher.update({where:{id:req.params.id},data:{name:clean(req.body.name)}});await audit({req,action:"PUBLISHER_UPDATED",entityType:"Publisher",entityId:item.id,before,after:item});return ok(res,item,"Đã cập nhật nhà xuất bản")});
adminRouter.delete("/publishers/:id",async(req,res)=>{const item=await prisma.publisher.findUnique({where:{id:req.params.id},include:{_count:{select:{books:true}}}});if(!item)throw new AppError(404,"Không tìm thấy nhà xuất bản");if(item._count.books)throw new AppError(409,"Không thể xóa nhà xuất bản đang có sách");await audit({req,action:"PUBLISHER_DELETED",entityType:"Publisher",entityId:item.id,before:{name:item.name}});await prisma.publisher.delete({where:{id:item.id}});return ok(res,null,"Đã xóa nhà xuất bản")});
adminRouter.patch("/locations/:id",async(req,res)=>{const before=await prisma.location.findUnique({where:{id:req.params.id}});if(!before)throw new AppError(404,"Không tìm thấy vị trí");const allowed=["area","cabinet","shelf","slot","note"];const data=Object.fromEntries(allowed.filter(k=>req.body[k]!==undefined).map(k=>[k,clean(req.body[k])]));const item=await prisma.location.update({where:{id:req.params.id},data});await audit({req,action:"LOCATION_UPDATED",entityType:"Location",entityId:item.id,before,after:item});return ok(res,item,"Đã cập nhật vị trí")});
adminRouter.delete("/locations/:id",async(req,res)=>{const item=await prisma.location.findUnique({where:{id:req.params.id},include:{_count:{select:{copies:true}}}});if(!item)throw new AppError(404,"Không tìm thấy vị trí");if(item._count.copies)throw new AppError(409,"Không thể xóa vị trí đang chứa bản sách");await audit({req,action:"LOCATION_DELETED",entityType:"Location",entityId:item.id,before:{area:item.area,cabinet:item.cabinet,shelf:item.shelf}});await prisma.location.delete({where:{id:item.id}});return ok(res,null,"Đã xóa vị trí")});

adminRouter.get("/books", async (req,res)=>{const p=Math.max(1,Number(req.query.page)||1),l=Math.min(100,Math.max(1,Number(req.query.limit)||20)),where={deletedAt:null,...(req.query.search?{title:{contains:String(req.query.search),mode:"insensitive"}}:{})};const[items,total]=await prisma.$transaction([prisma.book.findMany({where,include:{category:true,authors:{include:{author:true}},copies:true},orderBy:[{createdAt:"desc"},{id:"desc"}],skip:(p-1)*l,take:l}),prisma.book.count({where})]);return page(res,items,total,p,l)});
adminRouter.post("/books",validate(bookSchema),async(req,res)=>{const{authorIds,...body}=req.validated.body;const book=await prisma.book.create({data:{...body,slug:`${slugify(body.title)}-${body.bookCode.toLowerCase()}`,shortDescription:clean(body.shortDescription),editorialReview:clean(body.editorialReview),highlights:clean(body.highlights),recommendedFor:clean(body.recommendedFor),excerpt:clean(body.excerpt),authors:{create:authorIds.map(authorId=>({authorId}))}}});await audit({req,action:"BOOK_CREATED",entityType:"Book",entityId:book.id,after:{title:book.title,bookCode:book.bookCode}});return ok(res,book,"Đã thêm sách",201)});
adminRouter.patch("/books/:id",async(req,res)=>{const before=await prisma.book.findUnique({where:{id:req.params.id}});if(!before)throw new AppError(404,"Không tìm thấy sách");const allowed=["title","bookCode","isbn","language","publishedYear","shortDescription","editorialReview","highlights","recommendedFor","excerpt","showEditorialReview","featured","finePerDay","borrowDays","categoryId","publisherId","status"];const data=Object.fromEntries(allowed.filter(k=>req.body[k]!==undefined).map(k=>[k,typeof req.body[k]==="string"?clean(req.body[k]):req.body[k]]));if(data.title||data.bookCode)data.slug=`${slugify(data.title||before.title)}-${String(data.bookCode||before.bookCode).toLowerCase()}`;if(Array.isArray(req.body.authorIds)){if(!req.body.authorIds.length)throw new AppError(422,"Sách cần ít nhất một tác giả");data.authors={deleteMany:{},create:req.body.authorIds.map(authorId=>({authorId}))}}const book=await prisma.book.update({where:{id:req.params.id},data,include:{category:true,publisher:true,authors:{include:{author:true}},copies:true}});await audit({req,action:"BOOK_UPDATED",entityType:"Book",entityId:book.id,before:{title:before.title,status:before.status},after:{title:book.title,status:book.status}});return ok(res,book,"Đã cập nhật sách")});
adminRouter.patch("/books/:id/status",async(req,res)=>{if(!["VISIBLE","HIDDEN","DISCONTINUED"].includes(req.body.status))throw new AppError(422,"Trạng thái không hợp lệ");const book=await prisma.book.update({where:{id:req.params.id},data:{status:req.body.status}});await audit({req,action:"BOOK_STATUS_CHANGED",entityType:"Book",entityId:book.id,after:{status:book.status}});return ok(res,book,"Đã đổi trạng thái")});
adminRouter.delete("/books/:id",async(req,res)=>{const book=await prisma.book.findFirst({where:{id:req.params.id,deletedAt:null}});if(!book)throw new AppError(404,"Không tìm thấy sách");const active=await prisma.borrowRecord.count({where:{bookId:book.id,status:{in:["PENDING","APPROVED","BORROWING","OVERDUE"]}}});if(active)throw new AppError(409,"Không thể xóa sách đang có yêu cầu hoặc lượt mượn hoạt động");await prisma.$transaction([prisma.book.update({where:{id:book.id},data:{deletedAt:new Date(),status:"DISCONTINUED"}}),prisma.bookCopy.updateMany({where:{bookId:book.id,deletedAt:null},data:{deletedAt:new Date(),status:"INACTIVE"}})]);await audit({req,action:"BOOK_DELETED",entityType:"Book",entityId:book.id,before:{title:book.title}});return ok(res,null,"Đã xóa sách")});
adminRouter.post("/books/:id/cover",uploadImage.single("image"),async(req,res)=>{if(!req.file)throw new AppError(422,"Vui lòng chọn ảnh");const before=await prisma.book.findUnique({where:{id:req.params.id}});const image=await uploadBuffer(req.file.buffer,"acme-library/covers");const book=await prisma.book.update({where:{id:req.params.id},data:{coverUrl:image.url,coverPublicId:image.publicId}});await destroyImage(before.coverPublicId);return ok(res,book,"Đã cập nhật bìa sách")});

adminRouter.get("/book-copies",async(req,res)=>paged(req,res,prisma.bookCopy,{where:{deletedAt:null,...(req.query.bookId?{bookId:String(req.query.bookId)}:{}),...(req.query.status?{status:String(req.query.status)}:{})},include:{book:{select:{title:true,bookCode:true}},location:true},orderBy:[{createdAt:"desc"},{id:"desc"}]},20));
adminRouter.post("/book-copies",async(req,res)=>{const copy=await prisma.bookCopy.create({data:{copyCode:clean(req.body.copyCode),bookId:req.body.bookId,locationId:req.body.locationId,conditionNote:clean(req.body.conditionNote)}});await audit({req,action:"COPY_CREATED",entityType:"BookCopy",entityId:copy.id,after:{copyCode:copy.copyCode}});return ok(res,copy,"Đã thêm bản sách",201)});
adminRouter.patch("/book-copies/:id",async(req,res)=>ok(res,await prisma.bookCopy.update({where:{id:req.params.id},data:{locationId:req.body.locationId,conditionNote:clean(req.body.conditionNote)}}),"Đã cập nhật bản sách"));
adminRouter.patch("/book-copies/:id/status",async(req,res)=>{if(!["AVAILABLE","BORROWED","RESERVED","DAMAGED","LOST","INACTIVE"].includes(req.body.status))throw new AppError(422,"Trạng thái không hợp lệ");return ok(res,await prisma.bookCopy.update({where:{id:req.params.id},data:{status:req.body.status}}),"Đã đổi trạng thái")});
adminRouter.delete("/book-copies/:id",async(req,res)=>{const copy=await prisma.bookCopy.findFirst({where:{id:req.params.id,deletedAt:null}});if(!copy)throw new AppError(404,"Không tìm thấy bản sách");const active=await prisma.borrowRecord.count({where:{bookCopyId:copy.id,status:{in:["APPROVED","BORROWING","OVERDUE"]}}});if(active)throw new AppError(409,"Không thể xóa bản sách đang được mượn");const item=await prisma.bookCopy.update({where:{id:copy.id},data:{deletedAt:new Date(),status:"INACTIVE"}});await audit({req,action:"COPY_DELETED",entityType:"BookCopy",entityId:item.id,before:{copyCode:item.copyCode}});return ok(res,null,"Đã xóa bản sách")});

adminRouter.get("/borrow-requests",async(req,res)=>paged(req,res,prisma.borrowRecord,{where:req.query.status?{status:String(req.query.status)}:{},include:{user:{select:{id:true,firstName:true,lastMiddleName:true,email:true}},book:{select:{id:true,title:true,coverUrl:true}},bookCopy:true,fine:true},orderBy:[{createdAt:"desc"},{id:"desc"}]},20));
adminRouter.patch("/borrow-requests/:id/approve",async(req,res)=>ok(res,await approveBorrow(req.params.id,req.body.copyId,req),"Đã duyệt yêu cầu"));
adminRouter.patch("/borrow-requests/:id/reject",async(req,res)=>{const note=clean(req.body.note);if(!note)throw new AppError(422,"Cần nhập lý do từ chối");const record=await prisma.borrowRecord.findUnique({where:{id:req.params.id},select:{id:true,userId:true,status:true,book:{select:{title:true}}}});if(!record||record.status!=="PENDING")throw new AppError(409,"Yêu cầu không thể từ chối");await prisma.$transaction(async(tx)=>{const updated=await tx.borrowRecord.updateMany({where:{id:record.id,status:"PENDING"},data:{status:"CANCELLED",adminNote:note}});if(!updated.count)throw new AppError(409,"Yêu cầu không thể từ chối");await tx.notification.upsert({where:{dedupeKey:`borrow-rejected:${record.id}`},update:{title:"Yêu cầu mượn đã bị từ chối",message:`${record.book.title} — Lý do: ${note}`},create:{userId:record.userId,type:"BORROW",title:"Yêu cầu mượn đã bị từ chối",message:`${record.book.title} — Lý do: ${note}`,dedupeKey:`borrow-rejected:${record.id}`,data:{borrowRecordId:record.id,href:"/lich-su-muon"}}});await audit({req,action:"BORROW_REJECTED",entityType:"BorrowRecord",entityId:record.id,after:{note}},tx)});publishNotificationChange(record.userId,{action:"created",type:"BORROW"});return ok(res,null,"Đã từ chối yêu cầu")});
adminRouter.patch("/borrows/:id/return",async(req,res)=>{if(!["NORMAL","MINOR_TEAR","DAMAGED","LOST"].includes(req.body.condition))throw new AppError(422,"Tình trạng trả không hợp lệ");return ok(res,await returnBorrow(req.params.id,req.body,req),"Đã xác nhận trả sách")});
adminRouter.get("/borrows/overdue",async(_req,res)=>ok(res,await prisma.borrowRecord.findMany({where:{status:"OVERDUE"},include:{user:true,book:true,bookCopy:true,fine:true},orderBy:{dueDate:"asc"}})));

adminRouter.get("/fines",async(req,res)=>paged(req,res,prisma.fine,{where:req.query.status?{status:String(req.query.status)}:{},include:{borrowRecord:{include:{user:{select:{firstName:true,lastMiddleName:true,email:true}},book:{select:{title:true}}}}},orderBy:[{createdAt:"desc"},{id:"desc"}]},20));
async function resolveFine(req,res,status,amount){const fine=await prisma.fine.findUnique({where:{id:req.params.id}});if(!fine)throw new AppError(404,"Không tìm thấy phí phạt");if(!["UNPAID","REDUCED"].includes(fine.status))throw new AppError(409,"Phí phạt đã được xử lý");const note=clean(req.body.note);if(!note)throw new AppError(422,"Cần nhập ghi chú xử lý");const finalAmount=amount??fine.finalAmount;if(status==="REDUCED"&&Number(finalAmount)>=Number(fine.finalAmount))throw new AppError(422,"Mức phí mới phải thấp hơn mức phí hiện tại");const updated=await prisma.$transaction(async tx=>{const f=await tx.fine.update({where:{id:fine.id},data:{status,finalAmount,note,resolvedAt:status==="REDUCED"?null:new Date()}});await tx.borrowRecord.update({where:{id:fine.borrowRecordId},data:{fineStatus:status,fineAmount:finalAmount}});await audit({req,action:`FINE_${status}`,entityType:"Fine",entityId:fine.id,before:{status:fine.status,amount:Number(fine.finalAmount)},after:{status,amount:Number(finalAmount),note}},tx);return f});return ok(res,updated,"Đã xử lý phí phạt")}
adminRouter.patch("/fines/:id/mark-paid",(req,res)=>resolveFine(req,res,"PAID"));
adminRouter.patch("/fines/:id/waive",(req,res)=>resolveFine(req,res,"WAIVED",0));
adminRouter.patch("/fines/:id/reduce",(req,res)=>{const amount=Number(req.body.amount);if(!Number.isFinite(amount)||amount<0)throw new AppError(422,"Số tiền không hợp lệ");return resolveFine(req,res,"REDUCED",amount)});

adminRouter.get("/reviews",async(req,res)=>paged(req,res,prisma.review,{where:{...(req.query.status?{status:String(req.query.status)}:{}),...(req.query.rating?{rating:Number(req.query.rating)}:{})},include:{user:{select:{firstName:true,lastMiddleName:true,email:true}},book:{select:{title:true}}},orderBy:[{createdAt:"desc"},{id:"desc"}]},20));
const reviewStatus=(status)=>async(req,res)=>ok(res,await prisma.review.update({where:{id:req.params.id},data:{status,moderatedAt:new Date()}}),"Đã cập nhật đánh giá");
adminRouter.patch("/reviews/:id/approve",reviewStatus("PUBLISHED"));adminRouter.patch("/reviews/:id/hide",reviewStatus("HIDDEN"));
adminRouter.delete("/reviews/:id",async(req,res)=>{await prisma.review.delete({where:{id:req.params.id}});return ok(res,null,"Đã xóa đánh giá")});
adminRouter.get("/feedback",async(req,res)=>paged(req,res,prisma.feedback,{where:req.query.status?{status:String(req.query.status)}:{},include:{user:{select:{firstName:true,lastMiddleName:true,email:true}}},orderBy:[{createdAt:"desc"},{id:"desc"}]},20));
adminRouter.patch("/feedback/:id/reply",async(req,res)=>{const item=await prisma.feedback.update({where:{id:req.params.id},data:{adminReply:clean(req.body.reply),repliedAt:new Date(),status:"RESPONDED"}});await prisma.notification.create({data:{userId:item.userId,type:"FEEDBACK_REPLY",title:"Góp ý của bạn đã được phản hồi",message:`${item.subject}: ${clean(req.body.reply)}`}});publishNotificationChange(item.userId,{action:"created",type:"FEEDBACK_REPLY"});return ok(res,item,"Đã gửi phản hồi")});
adminRouter.patch("/feedback/:id/status",async(req,res)=>ok(res,await prisma.feedback.update({where:{id:req.params.id},data:{status:req.body.status}}),"Đã cập nhật trạng thái"));
adminRouter.delete("/feedback/:id",async(req,res)=>{const item=await prisma.feedback.findUnique({where:{id:req.params.id}});if(!item)throw new AppError(404,"Không tìm thấy góp ý");await audit({req,action:"FEEDBACK_DELETED",entityType:"Feedback",entityId:item.id,before:{subject:item.subject,status:item.status}});await destroyImage(item.attachmentPublicId);await prisma.feedback.delete({where:{id:item.id}});return ok(res,null,"Đã xóa góp ý")});
adminRouter.post("/notifications",async(req,res)=>{const users=req.body.userId?[{id:req.body.userId}]:await prisma.user.findMany({where:{status:"ACTIVE",deletedAt:null},select:{id:true}});await prisma.notification.createMany({data:users.map(u=>({userId:u.id,type:"SYSTEM",title:clean(req.body.title),message:clean(req.body.message)}))});users.forEach((user)=>publishNotificationChange(user.id,{action:"created",type:"SYSTEM"}));return ok(res,{recipients:users.length},"Đã gửi thông báo",201)});

adminRouter.post("/users",async(req,res)=>{const email=String(req.body.email||"").trim().toLowerCase(),password=String(req.body.password||""),role=req.body.role||"USER";if(!/^\S+@\S+\.\S+$/.test(email))throw new AppError(422,"Email không hợp lệ");if(password.length<10||!/[a-z]/.test(password)||!/[A-Z]/.test(password)||!/\d/.test(password))throw new AppError(422,"Mật khẩu cần ít nhất 10 ký tự, có chữ hoa, chữ thường và số");if(!["USER","ADMIN","SUPER_ADMIN"].includes(role))throw new AppError(422,"Vai trò không hợp lệ");if(role!=="USER"&&req.user.role!=="SUPER_ADMIN")throw new AppError(403,"Chỉ Super Admin được tạo quản trị viên");const user=await prisma.user.create({data:{email,lastMiddleName:clean(req.body.lastMiddleName||""),firstName:clean(req.body.firstName||""),phone:req.body.phone?clean(req.body.phone):null,passwordHash:await argon2.hash(password),role},select:{id:true,lastMiddleName:true,firstName:true,email:true,phone:true,role:true,status:true,createdAt:true}});await audit({req,action:"USER_CREATED",entityType:"User",entityId:user.id,after:{email:user.email,role:user.role}});return ok(res,user,"Đã tạo người dùng",201)});
adminRouter.get("/users",async(req,res)=>{const{currentPage:p,limit:l}=paginationParams(req,30),where={deletedAt:null,...(req.query.search?{OR:[{email:{contains:String(req.query.search),mode:"insensitive"}},{firstName:{contains:String(req.query.search),mode:"insensitive"}},{lastMiddleName:{contains:String(req.query.search),mode:"insensitive"}}]}:{})};const[items,total]=await prisma.$transaction([prisma.user.findMany({where,select:{id:true,lastMiddleName:true,firstName:true,email:true,phone:true,role:true,status:true,avatarUrl:true,createdAt:true,_count:{select:{borrows:true}}},orderBy:[{createdAt:"desc"},{id:"desc"}],skip:(p-1)*l,take:l}),prisma.user.count({where})]);return page(res,items,total,p,l)});
adminRouter.get("/users/:id",async(req,res)=>ok(res,await prisma.user.findUnique({where:{id:req.params.id},select:{id:true,lastMiddleName:true,firstName:true,email:true,phone:true,role:true,status:true,avatarUrl:true,zaloPhone:true,createdAt:true,borrows:{include:{book:true,fine:true},orderBy:{createdAt:"desc"}}}})));
adminRouter.patch("/users/:id/status",async(req,res)=>{if(req.params.id===req.user.id)throw new AppError(400,"Không thể tự khóa tài khoản");const user=await prisma.user.update({where:{id:req.params.id},data:{status:req.body.status}});await audit({req,action:"USER_STATUS_CHANGED",entityType:"User",entityId:user.id,after:{status:user.status}});return ok(res,{id:user.id,status:user.status},"Đã đổi trạng thái")});
adminRouter.patch("/users/:id/role",requireRole("SUPER_ADMIN"),async(req,res)=>{if(!["USER","ADMIN","SUPER_ADMIN"].includes(req.body.role))throw new AppError(422,"Vai trò không hợp lệ");const user=await prisma.user.update({where:{id:req.params.id},data:{role:req.body.role}});await audit({req,action:"USER_ROLE_CHANGED",entityType:"User",entityId:user.id,after:{role:user.role}});return ok(res,{id:user.id,role:user.role},"Đã đổi vai trò")});
adminRouter.delete("/users/:id",requireRole("SUPER_ADMIN"),async(req,res)=>{if(req.params.id===req.user.id)throw new AppError(400,"Không thể tự xóa tài khoản");const user=await prisma.user.findFirst({where:{id:req.params.id,deletedAt:null}});if(!user)throw new AppError(404,"Không tìm thấy người dùng");const active=await prisma.borrowRecord.count({where:{userId:user.id,status:{in:["PENDING","APPROVED","BORROWING","OVERDUE"]}}});if(active)throw new AppError(409,"Không thể xóa người dùng đang có lượt mượn hoạt động");await prisma.$transaction([prisma.user.update({where:{id:user.id},data:{deletedAt:new Date(),status:"LOCKED"}}),prisma.refreshToken.updateMany({where:{userId:user.id,revokedAt:null},data:{revokedAt:new Date()}})]);await audit({req,action:"USER_DELETED",entityType:"User",entityId:user.id,before:{email:user.email,role:user.role}});return ok(res,null,"Đã xóa người dùng")});
adminRouter.get("/settings",async(_req,res)=>ok(res,await prisma.systemSetting.upsert({where:{id:1},update:{},create:{id:1}})));
adminRouter.patch("/settings",async(req,res)=>{const allowed=["libraryName","logoUrl","defaultBorrowDays","defaultFinePerDay","maxConcurrentBorrows","allowRenewal","maxRenewals","requireBorrowApproval","requireReviewApproval","lockWithUnpaidFine","defaultTheme","allowThemeChange"];const data=Object.fromEntries(allowed.filter(k=>req.body[k]!==undefined).map(k=>[k,clean(req.body[k])]));const settings=await prisma.systemSetting.update({where:{id:1},data});await audit({req,action:"SETTINGS_UPDATED",entityType:"SystemSetting",entityId:"1",after:data});return ok(res,settings,"Đã lưu cài đặt")});
adminRouter.get("/reports/borrows",async(req,res)=>ok(res,await prisma.borrowRecord.groupBy({by:["status"],_count:true})));
adminRouter.get("/reports/fines",async(req,res)=>ok(res,await prisma.fine.groupBy({by:["status"],_sum:{finalAmount:true},_count:true})));
adminRouter.get("/reports/books",async(req,res)=>ok(res,await prisma.book.findMany({where:{deletedAt:null},orderBy:{borrowCount:"desc"},take:50,select:{id:true,title:true,bookCode:true,borrowCount:true}})));
